apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meu-app
  template:
    metadata:
      labels:
        app: meu-app
    spec:
      serviceAccountName: meu-sa
      containers:
      - name: meu-app
        image: renaneiras/meu-app:36fa14af6f4f785d7724555c07a60c40fd4ea893
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: meu-config
              key: LOG_LEVEL
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: meu-config
              key: DB_URL
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"