apiVersion: v1
kind: Service
metadata:
  name: meu-app-service
spec:
  selector:
    app: meu-app
  ports:
  - protocol: TCP
    port: 80  # Porta externa
    targetPort: 3000  # Porta do pod
  type: LoadBalancer  # Expõe pro mundo