apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meu-app
  template:
    metadata:
      labels:
        app: meu-app
    spec:
      serviceAccountName: meu-sa
      containers:
      - name: meu-app
        image: renaneiras/meu-app:f3f7a65e68d2c92126fa6f3aac7bedd24150bded
        env:
        - name: NEW_RELIC_APP_NAME
          value: "k8s-app"
        - name: NEW_RELIC_LICENSE_KEY
          value: "b4f962a57a224623c28eca7b518a7b0dFFFFNRAL"
        - name: NEW_RELIC_LOG
          value: "stdout"
        - name: NEW_RELIC_LOG_LEVEL
          value: "info"
        - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
          value: "true"
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: meu-config
              key: LOG_LEVEL
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: meu-config
              key: DB_URL
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"